name: Validate Dependabot Mergeable
description: |
  This action determines whether a Dependabot pull request can be merged based on the specified update type.

  ## Usage

  ```yaml
    steps:
      - name: Validate Dependabot Mergeable
        uses: tmknom/validate-dependabot-mergeable-action@v0
        with:
          update-type: version-update:semver-minor
          patch: true
          minor: true
          major: false
  ```

inputs:
  update-type:
    required: true
    description: The type of semantic versioning update. Acceptable values are `version-update:semver-patch`, `version-update:semver-minor`, and `version-update:semver-major`.
  patch:
    required: true
    description: Whether to merge the patch version.
  minor:
    required: true
    description: Whether to merge the minor version.
  major:
    required: true
    description: Whether to merge the major version.

outputs:
  mergeable:
    value: ${{ steps.check.outputs.mergeable }}
    description: Indicates whether the update type is mergeable.

runs:
  using: composite

  steps:
    - name: Check
      id: check
      env:
        PATCH: ${{ inputs.patch }}
        MINOR: ${{ inputs.minor }}
        MAJOR: ${{ inputs.major }}
        UPDATE_TYPE: ${{ inputs.update-type }}
      run: |
        set -x
        mergeable=false
        if [[ "${UPDATE_TYPE}" == "version-update:semver-patch" && "${PATCH}" == "true" ]]; then
          mergeable=true
        fi
        if [[ "${UPDATE_TYPE}" == "version-update:semver-minor" && "${MINOR}" == "true" ]]; then
          mergeable=true
        fi
        if [[ "${UPDATE_TYPE}" == "version-update:semver-major" && "${MAJOR}" == "true" ]]; then
          mergeable=true
        fi
        echo "mergeable=${mergeable}" >> "${GITHUB_OUTPUT}"
      shell: bash
