name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test-mergeable:
    name: Test mergeable ${{ matrix.case }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - case: patch
            update-type: version-update:semver-patch
          - case: minor
            update-type: version-update:semver-minor
          - case: major
            update-type: version-update:semver-major
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          update-type: ${{ matrix.update-type }}
          patch: true
          minor: true
          major: true

      - name: Verify
        env:
          MERGEABLE: ${{ steps.exercise.outputs.mergeable }}
        run: |
          set -x
          test "${MERGEABLE}" = "true"

  test-not-mergeable:
    name: Test not mergeable ${{ matrix.case }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - case: patch
            update-type: version-update:semver-patch
          - case: minor
            update-type: version-update:semver-minor
          - case: major
            update-type: version-update:semver-major
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          update-type: ${{ matrix.update-type }}
          patch: false
          minor: false
          major: false

      - name: Verify
        env:
          MERGEABLE: ${{ steps.exercise.outputs.mergeable }}
        run: |
          set -x
          test "${MERGEABLE}" = "false"
